config:
  credentials: []
  project_repos:
    github.com/CMCC-Foundation/ML4Fires:
      branch: main
      repo: https://github.com/CMCC-Foundation/ML4Fires
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/CMCC-Foundation/ML4Fires git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-wisteria-shark.sh
        container: qc.acc_muzzy-chocolate-kudu
  QC.Doc:
    repos:
      github.com/CMCC-Foundation/ML4Fires find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cobalt-giraffe.sh
        container: qc.doc_gloppy-aquamarine-sparrow
      github.com/CMCC-Foundation/ML4Fires git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-taupe-mayfly.sh
        container: qc.doc_geeky-myrtle-spoonbill
      github.com/CMCC-Foundation/ML4Fires markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-green-birman.sh
        container: qc.doc_frumpy-dandelion-caracal
  QC.Lic:
    repos:
      github.com/CMCC-Foundation/ML4Fires licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-pear-squirrel.sh
        container: qc.lic_sleazy-cerise-liger
  QC.Sec:
    repos:
      github.com/CMCC-Foundation/ML4Fires bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-ultramarine-uakari.sh
        container: qc.sec_leaky-viridian-toad
  QC.Sty:
    repos:
      github.com/CMCC-Foundation/ML4Fires flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sapphire-wasp.sh
        container: qc.sty_shabby-beige-serval
  QC.Uni:
    repos:
      github.com/CMCC-Foundation/ML4Fires pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ready-wheat-labradoodle.sh
        container: qc.uni_crabby-champagne-robin
  QC.Ver:
    repos:
      github.com/CMCC-Foundation/ML4Fires get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-persimmon-wombat.sh
        container: qc.ver_crabby-pumpkin-rhinoceros
timeout: 5400
